<link rel="stylesheet" href="<c:url value='/css/global.css'/>">
<link rel="stylesheet" href="<c:url value='/css/reset.css'/>">
<link rel="stylesheet" href="<c:url value='/css/epMCLayout.css'/>">
<link rel="stylesheet" href="<c:url value='/css/font.css'/>">
<link rel="stylesheet" href="<c:url value='/js/jquery.alerts.css'/>">
<link rel="stylesheet" type="text/css" href="${ctx}/css/bootstrap.min.css" media="all" />
<link rel="stylesheet" type="text/css" href="${ctx}/css/bootstrap-theme.min.css" media="all" />


