<script type="text/javascript" src="<c:url value='/js/jquery-1.8.3.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/lhgdialog/lhgdialog.min.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery.form.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/jquery.alerts.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/common-utils.js'/>"></script>
<script type="text/javascript" src="<c:url value='/js/number-format.js'/>"></script>
<script type="text/javascript" src="${ctx}/dwr/engine.js"></script>  
<script type="text/javascript" src="${ctx}/dwr/util.js"></script>
<script type="text/javascript">
var api = frameElement.api, W = api.opener;
var ctx = '${ctx}';
</script>
<script type="text/javascript" src="${ctx}/js/bootstrap.min.js"></script>

